### https://www.kaggle.com/abhishek/approaching-almost-any-nlp-problem-on-kaggle/notebook

### https://towardsdatascience.com/journey-to-the-center-of-multi-label-classification-384c40229bff
### https://towardsdatascience.com/multi-label-text-classification-with-scikit-learn-30714b7819c5

### https://machinelearningmastery.com/deep-learning-bag-of-words-model-sentiment-analysis/
### https://machinelearningmastery.com/prepare-movie-review-data-sentiment-analysis/

### https://www.analyticsvidhya.com/blog/2015/10/6-practices-enhance-performance-text-classification-model/


In [ ]:
No Punctuation
lowercase
Stopwords
Bag of Words
Tokenizer
Lemmatize
N-grams

In [1]:
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
corpus = ['This is the first document.',
'This document is the second document.',
'And this is the third one.',
'Is this the first document?',]

In [3]:
vectorizer = CountVectorizer()

In [4]:
vectorizer

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [5]:
X = vectorizer.fit_transform(corpus)


In [6]:
print(vectorizer.get_feature_names())


['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']


In [7]:
X.shape

(4, 9)

In [8]:
print(X.toarray())  

[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [9]:
corpus2 = ["THis is made by Rahul","Rahul is the best","The best is yet to come"]

In [10]:
vectorizer2 = CountVectorizer()

In [11]:
vectorizer2.fit_transform(corpus2)

<3x10 sparse matrix of type '<class 'numpy.int64'>'
	with 15 stored elements in Compressed Sparse Row format>

In [12]:
vectorizer2.get_feature_names()

['best', 'by', 'come', 'is', 'made', 'rahul', 'the', 'this', 'to', 'yet']

In [13]:
Y = vectorizer2.fit_transform(corpus2)

In [14]:
Y.toarray()

array([[0, 1, 0, 1, 1, 1, 0, 1, 0, 0],
       [1, 0, 0, 1, 0, 1, 1, 0, 0, 0],
       [1, 0, 1, 1, 0, 0, 1, 0, 1, 1]], dtype=int64)

In [15]:
import pandas as pd

In [16]:
d = {'serial': [10, 20,30], 'message': ['India is my Country','All Indians are my brothers and sisters India','India India is a strong nation']}
my_corpus = pd.DataFrame(data = d )

In [17]:
my_corpus.head()

message  serial
0                            India is my Country      10
1  All Indians are my brothers and sisters India      20
2                 India India is a strong nation      30

In [18]:
def tokenize(mess):
    return [word for word in mess.split() ]

In [19]:
tokenize('India is my country')

['India', 'is', 'my', 'country']

In [20]:
my_corpus['tokens'] = my_corpus['message'].apply(tokenize)

In [21]:
my_corpus.head()

message  serial  \
0                            India is my Country      10   
1  All Indians are my brothers and sisters India      20   
2                 India India is a strong nation      30   

                                              tokens  
0                           [India, is, my, Country]  
1  [All, Indians, are, my, brothers, and, sisters...  
2              [India, India, is, a, strong, nation]

In [22]:
# Z = CountVectorizer()
z1 = CountVectorizer(analyzer=tokenize).fit(my_corpus['message'])

In [23]:
z1.get_feature_names()

['All',
 'Country',
 'India',
 'Indians',
 'a',
 'and',
 'are',
 'brothers',
 'is',
 'my',
 'nation',
 'sisters',
 'strong']

In [24]:
z1.vocabulary_

{'All': 0,
 'Country': 1,
 'India': 2,
 'Indians': 3,
 'a': 4,
 'and': 5,
 'are': 6,
 'brothers': 7,
 'is': 8,
 'my': 9,
 'nation': 10,
 'sisters': 11,
 'strong': 12}

In [25]:
type(z1)

sklearn.feature_extraction.text.CountVectorizer

In [26]:
messages_bow = z1.transform(my_corpus['message'])

In [27]:
messages_bow.toarray()

array([[0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
       [1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0],
       [0, 0, 2, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1]], dtype=int64)

In [28]:
message3= my_corpus['message'][2]
bow3 = z1.transform([message3])
bow3.toarray()

array([[0, 0, 2, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1]], dtype=int64)

In [29]:
from sklearn.feature_extraction.text import TfidfTransformer

tfidf_transformer = TfidfTransformer().fit(messages_bow)
tfidf3 = tfidf_transformer.transform(bow3)
print(tfidf3)

  (0, 12)	0.44839402160692654
  (0, 10)	0.44839402160692654
  (0, 8)	0.3410152109911944
  (0, 4)	0.44839402160692654
  (0, 2)	0.5296574648148862


C:\Users\rahsood\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):


In [30]:
tfidf3.toarray()

array([[0.        , 0.        , 0.52965746, 0.        , 0.44839402,
        0.        , 0.        , 0.        , 0.34101521, 0.        ,
        0.44839402, 0.        , 0.44839402]])

In [31]:
z1.vocabulary_

{'All': 0,
 'Country': 1,
 'India': 2,
 'Indians': 3,
 'a': 4,
 'and': 5,
 'are': 6,
 'brothers': 7,
 'is': 8,
 'my': 9,
 'nation': 10,
 'sisters': 11,
 'strong': 12}

In [32]:
for x in z1.vocabulary_:
    print(x + ' ' + str(tfidf_transformer.idf_[z1.vocabulary_[x]]))
# tfidf_transformer.idf_[z1.vocabulary_['India']], tfidf_transformer.idf_[z1.vocabulary_['is']]

India 1.0
is 1.2876820724517808
my 1.2876820724517808
Country 1.6931471805599454
All 1.6931471805599454
Indians 1.6931471805599454
are 1.6931471805599454
brothers 1.6931471805599454
and 1.6931471805599454
sisters 1.6931471805599454
a 1.6931471805599454
strong 1.6931471805599454
nation 1.6931471805599454


In [33]:
messages_tfidf = tfidf_transformer.transform(messages_bow)
print(messages_tfidf.shape)

(3, 13)


C:\Users\rahsood\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):


In [34]:
messages_tfidf.toarray()

array([[0.        , 0.63174505, 0.37311881, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.4804584 , 0.4804584 ,
        0.        , 0.        , 0.        ],
       [0.37994462, 0.        , 0.22440141, 0.37994462, 0.        ,
        0.37994462, 0.37994462, 0.37994462, 0.        , 0.28895767,
        0.        , 0.37994462, 0.        ],
       [0.        , 0.        , 0.52965746, 0.        , 0.44839402,
        0.        , 0.        , 0.        , 0.34101521, 0.        ,
        0.44839402, 0.        , 0.44839402]])

In [35]:
messages_tfidf

<3x13 sparse matrix of type '<class 'numpy.float64'>'
	with 17 stored elements in Compressed Sparse Row format>